### ISSUE TITLE
Error when using python 3.9.6 

### ISSUE THREAD

**Issue by GuanqiDong92** [cfs-energy/radas#13]
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/62ef878f-2d41-434d-86a2-c79423de9432">
I want to install cfspopcon on Mac, but it seems to have failed to start well with the example. Do you have a similar problem?

**Comment by tbody-cfs** [comment]
@GuanqiDong92 I've opened https://github.com/cfs-energy/radas/pull/14 as a potential fix. You're welcome to try run that version of `radas` before we get it onto PyPi, following the instructions below
```
cd .. #change to some folder where you want to install radas
git clone git@github.com:cfs-energy/radas.git
cd radas
git checkout patch_shutil_for_py39
poetry install
poetry run radas --verbose
cd ../cfspopcon #change back to the cfspopcon repository
cp -r ../radas/radas_dir .
poetry run popcon example_cases/SPARC_PRD --show
```

**Comment by GuanqiDong92** [comment]
> git clone git@github.com:cfs-energy/radas.git

hi @tbody-cfs , when I try "poetry run radas", it comes to the following error..
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/43af167d-269c-4292-a0ec-7aa015264c3c">

I googled it, it seems clang/gcc have conflicts. But I don't know how to fix it, could you please help?

**Comment by tbody-cfs** [comment]
How did you install `gfortran`? I'd suggest using `brew install gcc` (https://fortran-lang.org/learn/os_setup/install_gfortran/#homebrew)

If you've already done that, can you paste here your `which gfortran`?

**Comment by GuanqiDong92** [comment]
> How did you install `gfortran`? I'd suggest using `brew install gcc` (https://fortran-lang.org/learn/os_setup/install_gfortran/#homebrew)
> 
> If you've already done that, can you paste here your `which gfortran`?

please forget my last information. After I reinstalled gcc and Python, I redone all the previous steps. However,
<img width="953" alt="image" src="https://github.com/user-attachments/assets/552e0d17-786b-41c7-a1d2-805a6bddabe9">

but I try install importlib-metadata, it did not work...

**Comment by tbody-cfs** [comment]
Have you run `poetry install` in  the `cfspopcon` folder?

If there are issues in `cfspopcon`, please re-open an issue in that repository. Also, for the future, please copy-paste the error message instead of screenshots, since this makes it easier for others to search and find related issues.

**Comment by GuanqiDong92** [comment]
> poetry run popcon example_cases/SPARC_PRD --show

@tbody-cfs thank you. it works now after I run poetry install in the cfspopcon

**Comment by GuanqiDong92** [comment]
> Have you run `poetry install` in the `cfspopcon` folder?
> 
> If there are issues in `cfspopcon`, please re-open an issue in that repository. Also, for the future, please copy-paste the error message instead of screenshots, since this makes it easier for others to search and find related issues.

@tbody-cfs thank you. it works now after I run poetry install in the cfspopcon folder.
